#
# Copyright (c) 2020 Juniper Networks, Inc. All rights reserved.
#

Import('DbEnv')
K8sClientEnv = DbEnv.Clone()

K8sClientEnv.Append(CPPPATH = ['/usr/include'])
K8sClientEnv.Append(CPPPATH = [K8sClientEnv['TOP'] + '/grpc'])
K8sClientEnv.Append(CPPPATH = [K8sClientEnv['TOP'] + '/database/k8s'])

#K8sClientEnv.Append(LIBPATH=['#build/lib'])

local_srcs = ['k8s_client.cc']

K8sClientEnv.Append(CXXFLAGS = '-Wall -std=c++11')
K8sClientEnv.Append(LDFLAGS = 'pkg-config --libs cpprest')

gen_files = K8sClientEnv.SandeshGenCpp('k8s.sandesh')
gen_srcs = K8sClientEnv.ExtractCpp(gen_files)

srcs = local_srcs + gen_srcs

libk8s_client = K8sClientEnv.Library('k8s_client', srcs)
K8sClientEnv.Install(K8sClientEnv['TOP_LIB'], libk8s_client)

K8sClientEnv.SConscript('test/SConscript', exports='K8sClientEnv', duplicate=0)
